/* Generated by Together */

#ifndef TGO4MDCONLINESLOTS_H
#define TGO4MDCONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
#include "hmdcconnectedtdc.h"

class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4MdcOnline;
class TGo4GUIRegistry;
class TGo4MdcOnlineStatus;
class TQRootCanvas;
class TPad;

class TGo4MdcOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4MdcOnlineSlots();
    TGo4MdcOnlineSlots(const char * name, const char * title, TGo4MdcOnline * p);

    void SetGUI(TGo4MdcOnline *);
    TGo4MdcOnline *GetGUI(){return fxTGo4MdcOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void AddObject(TNamed * ,TQRootCanvas*,TPad*);
    void UpdateGUI(TObject*);
    HMdcConnectedTdc* getMdcLookup(){return mdclookup;}
    ClassDef(TGo4MdcOnlineSlots, 1);
    
private:    
    TGo4MdcOnline *fxTGo4MdcOnline; //!
    TGo4MdcOnlineStatus *fxTGo4MdcOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
    HMdcConnectedTdc* mdclookup;
};
#endif //TGO4MDCONLINESLOTS_H
