##############################################################################
#
#  Makefile for Hydra library libOnline.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Online

SOURCE_FILES :=	honlinecontrol.cc	\
		hparameter.cc		\
		hcontour.cc		\
		hcontourcont.cc		\
		hconditionout.cc	\
		hlocalcondition.cc	\
		hexpstring.cc		\
		hlocalcont.cc		\
		hdetset.cc		\
		hdetsetcont.cc		\
		hindextransform.cc	\
		herror.cc		\
		hhistogram.cc		\
		hhistocont.cc		\
		hglobalcondition.cc	\
		hglobalcont.cc		\
		honlprocessevent.cc	\
		hconsistency.cc		\
		hmemorycheck.cc		\
		hcalclocation.cc	\
		hconsistencywarn.cc	\
		honlobjbrowser.cc	\
		hbrowserdb.cc		\
		hprojection.cc		\
		hhistovisual.cc		\
		hdisplaydb.cc		\
		honlmainwindow.cc	\
		hconfigrun.cc		\
		hconfigure.cc		\
		hslice.cc		\
		hpreferences.cc		\
		hcontourmanager.cc	\
		hconversion.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
