/* Generated by Together */

#ifndef TGO4HODOONLINESTATUS_H
#define TGO4HODOONLINESTATUS_H
#include "Go4StatusBase/TGo4Status.h"
#include "TObjArray.h"
#include "TIterator.h"
#include "TObject.h"

class TGo4HodoOnlineStatus : public TGo4Status {
public:    

    ~TGo4HodoOnlineStatus();

    TGo4HodoOnlineStatus(Text_t *Name, Text_t * Title);
    TObject* OverWriteLocalObject(TNamed * fxData_Local);
    TIterator *GetLocalListIter(){return LocalListIter;}
    TObjArray *GetLocalListStatus();
    TObject* GetObjectfromLocalList(const Char_t *ObjectAt);
    ClassDef(TGo4HodoOnlineStatus,1);

private:
	
	TObjArray *LocalListContent;
	TIterator* LocalListIter;        
    
};
#endif //TGO4HODOONLINESTATUS_H
