/* Generated by Together */

#ifndef TGO4TRIGGERONLINESTATUS_H
#define TGO4TRIGGERONLINESTATUS_H
#include "Go4StatusBase/TGo4Status.h"
#include "TObjArray.h"
#include "TIterator.h"
#include "TObject.h"

class TGo4TriggerOnlineStatus : public TGo4Status {
public:    

    ~TGo4TriggerOnlineStatus();

    TGo4TriggerOnlineStatus(Text_t *Name, Text_t * Title);
    TObject*  OverWriteLocalObject(TNamed * fxData_Local);
    TIterator *GetLocalListIter(){return LocalListIter;}
    TObjArray *GetLocalListStatus();
    TObject* GetObjectfromLocalList(const Char_t *ObjectAt);
    ClassDef(TGo4TriggerOnlineStatus,1);

private:
	
	TObjArray *LocalListContent;
	TIterator* LocalListIter;        
    
};
#endif //TGO4TRIGGERONLINESTATUS_H
