/* Generated by Together */

#ifndef TGO4SHOWERONLINESTATUS_H
#define TGO4SHOWERONLINESTATUS_H
#include "Go4StatusBase/TGo4Status.h"
#include "TObjArray.h"
#include "TIterator.h"
#include "TObject.h"

class TGo4ShowerOnlineStatus : public TGo4Status {
public:    

    ~TGo4ShowerOnlineStatus();

    TGo4ShowerOnlineStatus(Text_t *Name, Text_t * Title);
    TObject* OverWriteLocalObject(TNamed * fxData_Local);
    TIterator *GetLocalListIter(){return LocalListIter;}
    TObjArray *GetLocalListStatus();
    TObject* GetObjectfromLocalList(const Char_t *ObjectAt);
    ClassDef(TGo4ShowerOnlineStatus,1);

private:
	
	TObjArray *LocalListContent;
	TIterator* LocalListIter;        
    
};
#endif //TGO4SHOWERONLINESTATUS_H
