/* Generated by Together */

#include "TGo4HadesConfigStatus.h"
#include "Go4LockGuard/TGo4LockGuard.h"

TGo4HadesConfigStatus::TGo4HadesConfigStatus(Text_t *Name, Text_t * Title)
			:TGo4Status(Name)
{


  
}
TGo4HadesConfigStatus::~TGo4HadesConfigStatus()
{

}



ClassImp(TGo4HadesConfigStatus)
