##############################################################################
#
#  Makefile for Hydra library libRich.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Rich

SOURCE_FILES :=	hdeco.cc			\
		hrichanalysis.cc		\
		hrichanalysispar.cc		\
		hrichanalysissim.cc		\
		hrichcal.cc			\
		hrichcalibrater.cc		\
		hrichcleaner.cc			\
		hrichthresholdpar.cc		\
		hrichcalpar.cc			\
		hrichcalparcell.cc		\
		hrichcalsim.cc			\
		hrichcorrelatorpar.cc		\
		hrichcontfact.cc		\
		hrichcuttracklet.cc		\
		hrichcuto.cc			\
		hrichcutpair.cc			\
		hrichdetector.cc		\
		hrichdigitisationpar.cc		\
		hrichdigitizer.cc		\
		hrichframe.cc			\
		hrichgeantreader.cc		\
		hrichgeometrypar.cc		\
		hrichhit.cc			\
		hrichhitcandidate.cc		\
		hrichhitfilter.cc		\
		hhitmatchfilter.cc		\
		hdihitmatchfilter.cc		\
		hrichhitheader.cc		\
		hrichhitselection.cc		\
		hrichhitsim.cc			\
		hrichlabel.cc			\
		hrichmappingpar.cc		\
		hrichobjfilter.cc		\
		hrichpad.cc			\
		hrichpadclean.cc		\
		hrichpadfilter.cc		\
		hrichpadgraph.cc		\
		hrichpadlabel.cc		\
		hrichpadsignal.cc		\
		hrichparasciifileio.cc		\
		hrichparhadasciifileio.cc	\
		hrichparrootfileio.cc		\
		hrichparset.cc			\
		hrichparticleidentifier.cc	\
		hrichpedestalraw.cc		\
		hrichpedestalupdate.cc		\
		hrichpedrawnew.cc		\
		hrichpid.cc			\
		hrichraw.cc			\
		hrichringfind.cc		\
		hrichringfindsim.cc		\
		hrichsectorpar.cc		\
		hrichtaskset.cc			\
		hrichtrack.cc			\
		hrichunpackercal99.cc		\
		hrichunpackercurrent.cc		\
		hrichunpackerraw99.cc		\
		hrichwire.cc			\
		hrichwiresignal.cc
# removed from Makefile, but not from CVS
#		hrichpedcalnew.cc		\
#		hrichpedestalcal.cc		\
#		hrichunpackercal.cc		\
#		hrichunpacker.cc		\
#		hrichunpackerraw.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
