##############################################################################
#
#  Makefile for Hydra library libTofUtil.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := TofUtil

SOURCE_FILES :=	hlvl1evtfilter.cc	\
		htimelvl1evtfilter.cc	\
		htofoffliner.cc
# files not included in build process but still in CVS
#		htofmonitor.cc		\
#		htofconfigpanel.cc	\
#		htofsector.cc		\
#		htofeventdisplay.cc	\
#		htofhistaction.cc	\
#		htofrod.cc		\
#		htofgeom.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
