##############################################################################
#
#  Makefile for Hydra library libMdcPid.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := MdcPid

SOURCE_FILES :=	hmdcdedxhists.cc	\
		hmdcwireinfo.cc		\
		hcategorymaker.cc	\
		hmdcextractors.cc

# bugus file, which do not compile
#		hmdccpselector.cc	\
#		hmdccpcutsfinder.cc	\
#		hmdcextractor.cc	\
#		hmdcfunc1.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
