/* Generated by Together */

#ifndef TGO4HODOONLINESLOTS_H
#define TGO4HODOONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4HodoOnline;
class TGo4GUIRegistry;
class TGo4HodoOnlineStatus;
class TQRootCanvas;
class TPad;

class TGo4HodoOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4HodoOnlineSlots();
    TGo4HodoOnlineSlots(const char * name, const char * title, TGo4HodoOnline * p);

    void SetGUI(TGo4HodoOnline *);
    TGo4HodoOnline *GetGUI(){return fxTGo4HodoOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void AddObject(TNamed * ,TQRootCanvas*,TPad*);
    void UpdateGUI(TObject*);
    ClassDef(TGo4HodoOnlineSlots, 1);
    
private:    
    TGo4HodoOnline *fxTGo4HodoOnline; //!
    TGo4HodoOnlineStatus *fxTGo4HodoOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4HODOONLINESLOTS_H
