##############################################################################
#
#  Makefile for Hydra library libRpc.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Rpc

SOURCE_FILES :=	hrpcraw.cc		\
		hrpcunpacker.cc		\
		hrpccontfact.cc		\
		hrpclookup.cc		\
		hrpcdetector.cc		\
		hrpcparrootfileio.cc	\
		hrpcparasciifileio.cc	\
		hrpccal.cc              \
		hrpccalsim.cc           \
		hrpcdigipar.cc          \
		hrpctrbunpacker.cc      \
		hrpctaskset.cc          \
		hrpcdigitizer.cc



include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
