/* Generated by Together */

#ifndef TGO4SHOWERONLINESLOTS_H
#define TGO4SHOWERONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4ShowerOnline;
class TGo4GUIRegistry;
class TGo4ShowerOnlineStatus;
class TQRootCanvas;
class TPad;

class TGo4ShowerOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4ShowerOnlineSlots();
    TGo4ShowerOnlineSlots(const char * name, const char * title, TGo4ShowerOnline * p);

    void SetGUI(TGo4ShowerOnline *);
    TGo4ShowerOnline *GetGUI(){return fxTGo4ShowerOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void AddObject(TNamed * ,TQRootCanvas*,TPad*);
    void UpdateGUI(TObject*);
    ClassDef(TGo4ShowerOnlineSlots, 1);
    
private:    
    TGo4ShowerOnline *fxTGo4ShowerOnline; //!
    TGo4ShowerOnlineStatus *fxTGo4ShowerOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4SHOWERONLINESLOTS_H
