##############################################################################
#
#  Makefile for Hydra library libStart.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Start

SOURCE_FILES :=	hstartdetector.cc	\
		hstartraw.cc		\
		hstartcal.cc		\
		hstarthit.cc		\
		hstarttaskset.cc	\
		hstartcontfact.cc	\
		hstartunpacker.cc	\
		hstartcalibrater.cc	\
		hstarthitf.cc		\
		hstartcalpar.cc		\
		hstartlookup.cc		\
		hstartgeompar.cc	\
		hstartselfcopar.cc	\
		hstartparrootfileio.cc	\
		hstartparasciifileio.cc	\
		htboxdetector.cc	\
		htboxchan.cc		\
		htboxchansum.cc		\
		htboxsum.cc		\
		hscalersreader.cc	\
		hstarthitfproton.cc	\
		htboxunpacker.cc	\
		hlatchunpacker.cc
# removed from Makefile, but not from CVS
#		hstartmonitor.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
