/* Generated by Together */

#ifndef TGO4HADESONLINEPANELSLOTS_H
#define TGO4HADESONLINEPANELSLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4HadesOnlinePanel;
class TGo4GUIRegistry;
class TGo4HadesOnlinePanelStatus;
class TQRootCanvas;
class TPad;

class TGo4HadesOnlinePanelSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4HadesOnlinePanelSlots();    
    TGo4HadesOnlinePanelSlots(const Char_t * name, const Char_t * title, TGo4HadesOnlinePanel * p);	

    void SetGUI(TGo4HadesOnlinePanel *);
    TGo4HadesOnlinePanel *GetGUI(){return fxTGo4HadesOnlinePanel; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void AddObject(TNamed * ,TQRootCanvas*,TPad*);
    void UpdateGUI(TObject*);
    ClassDef(TGo4HadesOnlinePanelSlots, 1);
    
private:    
    TGo4HadesOnlinePanel *fxTGo4HadesOnlinePanel; //!
    TGo4HadesOnlinePanelStatus *fxTGo4HadesOnlinePanelStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4HADESONLINEPANELSLOTS_H
