/* Generated by Together */

#ifndef TGO4TRIGGERONLINESLOTS_H
#define TGO4TRIGGERONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4TriggerOnline;
class TGo4GUIRegistry;
class TGo4TriggerOnlineStatus;
class TQRootCanvas;
class TPad;

class TGo4TriggerOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4TriggerOnlineSlots();
    TGo4TriggerOnlineSlots(const Char_t * name, const Char_t * title, TGo4TriggerOnline * p);

    void SetGUI(TGo4TriggerOnline *);
    TGo4TriggerOnline *GetGUI(){return fxTGo4TriggerOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void AddObject(TNamed * ,TQRootCanvas*,TPad*);
    void UpdateGUI(TObject*);
    ClassDef(TGo4TriggerOnlineSlots, 1);
    
private:    
    TGo4TriggerOnline *fxTGo4TriggerOnline; //!
    TGo4TriggerOnlineStatus *fxTGo4TriggerOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4TRIGGERONLINESLOTS_H
