##############################################################################
#
#  Makefile for Hydra library libPairs.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Pairs

SOURCE_FILES :=	hpair.cc		\
		hpaircontfact.cc	\
		hpaircutpar.cc		\
		hpairdata.cc		\
		hpaireffpar.cc		\
		hpairfiller.cc		\
		hpairfilter.cc		\
		hpairfl.cc		\
		hpairgeantdata.cc	\
		hpairhisto.cc		\
		hpairqa.cc		\
		hpairsim.cc		\
		hpairevtfilter.cc	\
		hpairevtmixer.cc	\
		hpairext.cc		\
		hpairsimext.cc
# files not included in build process but still in CVS
#		hpidparticleext.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
