##############################################################################
#
#  Makefile for Hydra library libShowerTofino.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := ShowerTofino

SOURCE_FILES :=	hshowerhittof.cc		\
		hshowertofinocorrelator.cc	\
		hshowerhittoftrack.cc		\
		hshowerhittoftrackmatcher.cc	\
		hshowertofpid.cc		\
		hshowertofpidfinder.cc		\
		hshowertofpidtrack.cc		\
		hshowertofpidtrackmatcher.cc	\
		hshowertofinotaskset.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
