/* Generated by Together */

#ifndef TGO4TOFINOONLINESLOTS_H
#define TGO4TOFINOONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4TofinoOnline;
class TGo4GUIRegistry;
class TGo4TofinoOnlineStatus;
class TQRootCanvas;
class TPad;

class TGo4TofinoOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4TofinoOnlineSlots();
    TGo4TofinoOnlineSlots(const char * name, const char * title, TGo4TofinoOnline * p);

    void SetGUI(TGo4TofinoOnline *);
    TGo4TofinoOnline *GetGUI(){return fxTGo4TofinoOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void AddObject(TNamed * ,TQRootCanvas*,TPad*);
    void UpdateGUI(TObject*);
    ClassDef(TGo4TofinoOnlineSlots, 1);
    
private:    
    TGo4TofinoOnline *fxTGo4TofinoOnline; //!
    TGo4TofinoOnlineStatus *fxTGo4TofinoOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4TOFINOONLINESLOTS_H
