##############################################################################
#
#  Makefile for Hydra library libTofino.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Tofino

SOURCE_FILES :=	htofinodetector.cc		\
		htofinoraw.cc			\
		htofinocal.cc			\
		htofinocalsim.cc		\
		htofinounpacker.cc		\
		htofinodigitizer.cc		\
		htofinocalibrater.cc		\
		htofinoparset.cc		\
		htofinocontfact.cc		\
		htofinocalpar.cc		\
		htofinocalparcell.cc		\
		htofinoshowermap.cc		\
		htofinoshowermapcell.cc		\
		htofinolookup.cc		\
		htofinogeompar.cc		\
		htofinotaskset.cc		\
		htofinoparrootfileio.cc		\
		htofinoparhadasciifileio.cc	\
		htofinoparasciifileio.cc	\
		htofinocalsimfilter.cc		\
		htofinodigitpar.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
