/* Generated by Together */

#ifndef TGO4MDCONLINESTATUS_H
#define TGO4MDCONLINESTATUS_H
#include "Go4StatusBase/TGo4Status.h"
#include "TObjArray.h"
#include "TIterator.h"
#include "TObject.h"

class TGo4MdcOnlineStatus : public TGo4Status {
public:    

    ~TGo4MdcOnlineStatus();

    TGo4MdcOnlineStatus(Text_t *Name, Text_t * Title);
    TObject* OverWriteLocalObject(TNamed * fxData_Local);
    TIterator *GetLocalListIter(){return LocalListIter;}
    TObjArray *GetLocalListStatus();
    TObject* GetObjectfromLocalList(const char *ObjectAt);
    ClassDef(TGo4MdcOnlineStatus,1);

private:
	
	TObjArray *LocalListContent;
	TIterator* LocalListIter;        
    
};
#endif //TGO4MDCONLINESTATUS_H
