/* Generated by Together */

#ifndef TGO4WALLONLINESLOTS_H
#define TGO4WALLONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4WallOnline;
class TGo4GUIRegistry;
class TGo4WallOnlineStatus;
class TQRootCanvas;
class TPad;

class TGo4WallOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4WallOnlineSlots();
    TGo4WallOnlineSlots(const char * name, const char * title, TGo4WallOnline * p);

    void SetGUI(TGo4WallOnline *);
    TGo4WallOnline *GetGUI(){return fxTGo4WallOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void AddObject(TNamed * ,TQRootCanvas*,TPad*);
    void UpdateGUI(TObject*);
    ClassDef(TGo4WallOnlineSlots, 1);
    
private:    
    TGo4WallOnline *fxTGo4WallOnline; //!
    TGo4WallOnlineStatus *fxTGo4WallOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4WALLONLINESLOTS_H
