##############################################################################
#
#  Makefile for Hydra library libKick.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Kick

SOURCE_FILES :=	hsurface.cc			\
		hkicktaskset.cc			\
		hkickplane.cc			\
		hkicktrackf.cc			\
		hkickdetdigi.cc			\
		hkickgrid.cc			\
		hkicktrackfpar.cc		\
		hkickimpact.cc			\
		hkickcandidate.cc		\
		hkickcandidateevaluator.cc	\
		htofhitsim2.cc			\
		hkickparasciifileio.cc		\
		hkicktrack.cc			\
		hkicktask.cc			\
		hkickmassfit.cc			\
		hkickparrootfileio.cc		\
		hkickcontfact.cc		\
		hkickplane2.cc			\
		hkickmatchpar.cc		\
		hkickresolution.cc		\
		hkicktrackfsim.cc		\
		hkickcandidateevaluatorsim.cc	\
		hkickcandidateevaluatorsim2.cc	\
		hkickcandidatematrix.cc		\
		hkickshowertrans.cc		\
		hludecomposer.cc		\
		hsavitzkygolay.cc		\
		hrtfunctional.cc		\
		hrtfitter.cc			\
		hrtsegmentref.cc		\
		hrttrackfind.cc			\
		hrttrackfindsim.cc		\
		hrttrackingpar.cc		\
		hrtmdchit2segsim.cc		\
		hrtmetamatch.cc			\
		hrtmetatrack.cc			\
		hrtmdctrk.cc			\
		hrtextractor.cc			\
		hrtmdcres.cc			\
		hkicktracksim.cc		\
		hrtmetacorrelator.cc		\
		hrtm3metamatch.cc		\
		hrtmetaseg.cc			\
		hrtm3metamatchsim.cc		\
		hrtmetasegsim.cc		\
		hkickparinfo.cc			\
		hrtmdctrksim.cc			\
		hrttrackio.cc			\
		hrtmetatrackio.cc		\
		hrtmdctrackio.cc		\
		hrttrackevaluator.cc		\
		hrtmdctrackiosim.cc		\
		hrtmetamatcheff.cc		\
		hrtmetacorrelatorsim.cc		\
		hrtseg2hit.cc			\
		hrtefficiency.cc		\
		hrtparamfinder.cc		\
		hrtmatchingpar.cc		\
		hrtmeasurement.cc		\
		hrttracksiminspect.cc		\
		hrtsavgolmanager.cc		\
		hrtdata.cc			\
		hrtsavgolpar.cc			\
		hrtgrid.cc			\
		hrttypematrix.cc		\
		hkickpionimass.cc		\
		hkicktrackfb.cc			\
		hkicktrackfbsim.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
