##############################################################################
#
#  Makefile for Hydra library libAlignment.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Alignment

SOURCE_FILES :=	hmdcaligner.cc		\
		hmdcgeomparf.cc		\
		hmdcmetahit.cc		\
		hmdcmetaaligner.cc	\
		hmetaaligner.cc		\
		hmetaalignerutil.cc	\
		hmetaalignerutil2.cc	\
		hmdcaligner3M.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
