/* Generated by Together */

#ifndef TGO4PHYSICSONLINESLOTS_H
#define TGO4PHYSICSONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"

class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4PhysicsOnline;
class TGo4GUIRegistry;
class TGo4PhysicsOnlineStatus;
class TQRootCanvas;
class TPad;

class TGo4PhysicsOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4PhysicsOnlineSlots();
    TGo4PhysicsOnlineSlots(const char * name, const char * title, TGo4PhysicsOnline * p);

    void SetGUI(TGo4PhysicsOnline *);
    TGo4PhysicsOnline *GetGUI(){return fxTGo4PhysicsOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void AddObject(TNamed * ,TQRootCanvas*,TPad*);
    void UpdateGUI(TObject*);
    ClassDef(TGo4PhysicsOnlineSlots, 1);
    
private:    
    TGo4PhysicsOnline *fxTGo4PhysicsOnline; //!
    TGo4PhysicsOnlineStatus *fxTGo4PhysicsOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4PHYSICSONLINESLOTS_H
