##############################################################################
#
#  Makefile for Hydra library libPid.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Pid

SOURCE_FILES :=	hpidhitdata.cc			\
		hpidtrackdata.cc		\
		hpidtrackcand.cc		\
	  	hpidtrackcandsim.cc		\
	  	hpidgeanttrackset.cc		\
	  	hpidtrackfiller.cc		\
		hpidparcont.cc			\
		hpidparasciifileio.cc		\
		hpidparrootfileio.cc		\
		hpidcontfact.cc			\
		hpidtrackfillerpar.cc		\
		hpidhistogramscont.cc		\
		hpidparticlefiller.cc		\
		hpidparticle.cc			\
		hpidparticlesim.cc		\
		hpidreconstructor.cc		\
		hpidreconstructorpar.cc		\
		hpidalgorithm.cc		\
		hpidalgmomvsbeta.cc		\
		hpidalgmomvsbetapar.cc		\
		hpidalgringproperties.cc	\
		hpidalgringpropertiespar.cc	\
	        hpidcandidate.cc		\
	        hpidgaussconf.cc		\
		hpidalgshowerpar.cc		\
		hpidalgshower.cc		\
		hpidalgstandcuts.cc		\
		hpidalgstandcutspar.cc		\
		hpidtofrec.cc			\
		hpidalghardcuts.cc		\
		hpidalghardcutspar.cc		\
		hpidskiptrigger.cc		\
		hpidtaskset.cc			\
		hpidalgmdceloss.cc		\
		hpidalgmdcelosspar.cc           \
		hpiddilepton.cc                 \
                hpidcpparam.cc \
                hpidevtinfofiller.cc \
                hpidevtinfo.cc 

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
