##############################################################################
#
#  Makefile for Hydra library libTof.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Tof

SOURCE_FILES :=	htofcal.cc		\
		htofcalibrater.cc	\
		htofdigitizer.cc	\
		htofhit.cc		\
		htofhitf.cc		\
		htofraw.cc		\
		htofunpacker.cc		\
		htofcontfact.cc		\
		htofcalpar.cc		\
		htofdigipar.cc		\
		htoflookup.cc		\
		htofdetector.cc		\
		htofrawsimfilter.cc	\
		htofgeantreader.cc	\
		htofrawsim.cc		\
		htofcalsim.cc		\
		htofhitsim.cc		\
		htofhitfsim.cc		\
		htoftrigger.cc		\
		htofunpacker99.cc	\
		htofparrootfileio.cc	\
		htofparasciifileio.cc	\
		htofgeompar.cc		\
		htofclusterf.cc		\
		htofcluster.cc		\
		htofclusterfsim.cc	\
		htofclustersim.cc	\
		htofclusterfpar.cc	\
		htoftaskset.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
