/* Generated by Together */

#ifndef TGO4TOFINOONLINESTATUS_H
#define TGO4TOFINOONLINESTATUS_H
#include "Go4StatusBase/TGo4Status.h"
#include "TObjArray.h"
#include "TIterator.h"
#include "TObject.h"

class TGo4TofinoOnlineStatus : public TGo4Status {
public:    

    ~TGo4TofinoOnlineStatus();

    TGo4TofinoOnlineStatus(Text_t *Name, Text_t * Title);
    void OverWriteLocalObject(TNamed * fxData_Local);
    TIterator *GetLocalListIter(){return LocalListIter;}
    TObjArray *GetLocalListStatus();
    TObject* GetObjectfromLocalList(const char *ObjectAt);
    ClassDef(TGo4TofinoOnlineStatus,1);

private:
	
	TObjArray *LocalListContent;
	TIterator* LocalListIter;        
    
};
#endif //TGO4TOFINOONLINESTATUS_H
