##############################################################################
#
#  Makefile for Hydra library libPidUtil.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := PidUtil

SOURCE_FILES :=	hpidfl.cc		\
		hpidmdcfunc.cc		\
		hpidpdfmaker.cc		\
		htrackntuplemaker.cc	\
		hpidperformacetest.cc	\
		hpidsingleleptoneff.cc	\
		hpidsingletrackeff.cc	\
		hpidefficiencycalculation.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
