##############################################################################
#
#  Makefile for Hydra library libPhyAna.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := PhyAna

SOURCE_FILES :=	hphysicsconstants.cc	\
		hphysicsevent.cc	\
		hphysicsmixedevent.cc	\
		hcut.cc			\
		hcuttrack.cc		\
		hcutparticle.cc		\
		hcutleptonid.cc		\
		hcuthadronid.cc		\
		hparticle.cc		\
		hparticlesim.cc		\
		hparticlesrc.cc		\
		hdilepton.cc		\
		hpseudotracking.cc	\
		hparticlefiller.cc	\
		hparticlesimfiller.cc	\
		hdileptonfiller.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
