##############################################################################
#
#  Makefile for Hydra library libTriggerUtil.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := TriggerUtil

SOURCE_FILES :=	hrichanalysisIPU.cc		\
		hrichanalysisIPUSim.cc		\
		hrichringfindIPU.cc		\
		hrichringfindIPUSim.cc		\
		hrichIPUtaskset.cc		\
		hrichhitIPU.cc			\
		hrichhitIPUSim.cc		\
		hrichIPUparlocmax.cc		\
		hrichIPUparpattern.cc		\
		hrichIPUparthresholds.cc	\
		hrichIPUremake.cc		\
		hrichIPUremakeSim.cc		\
		hrichIPUmap.cc			\
		hlocmaxfilter.cc		\
		hlocmaxfilterSim.cc		\
		hshowercalibraterIPU.cc		\
		hshowerhitfinderIPU.cc		\
		hshowercalIPU.cc		\
		hshowerhitIPU.cc		\
		hshowercheckIPU.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
