/* Generated by Together */

#ifndef TGO4ANALYSISMAINRUNNABLE_H
#define TGO4ANALYSISMAINRUNNABLE_H
#include "Go4ThreadManager/TGo4Runnable.h"
#include "Go4Socket/TGo4Socket.h"
#include "TGo4Hades.h"


class TGo4HadesClient;


#ifndef __MAKECINT__
   #include "Go4Queue/TGo4ThreadQueue.h"
class TGo4BufferQueue;
class TGo4ObjectQueue;
#else
   class TGo4ThreadQueue<TGo4Command>;
   class TGo4ThreadQueue<TGo4Status>;
   class TGo4ThreadQueue<TNamed>;
#endif



/**
 * Main Runnable of the go4 analysis. Takes commands out of
 * command queue and processes them, then acts on the
 * analysis framework MainCycle method to process the analysis.
 * @since 11-Jan-2001
 * @stereotype thread 
 * @author J. Adamczewski
 */
class TGo4HadesMainRunnable : public TGo4Runnable {
public:

   TGo4HadesMainRunnable(Text_t* name, TGo4HadesClient* cli);


   virtual ~TGo4HadesMainRunnable();   

   virtual Int_t Run(void*);

   virtual Int_t PreRun(void * );

   virtual Int_t PostRun(void * );

private:    
//!
//!
//!

   /** @supplierCardinality 1 
    * @directed
    * @clientCardinality 0..1*/
   TGo4Hades * fxAnalysis; //!

   TGo4HadesMainRunnable();
   
ClassDef(TGo4HadesMainRunnable,1)   
};
#endif //TGO4ANALYSISMAINRUNNABLE_H
