#!/bin/ksh
#
# set environnement variable for online
# version of hydra base classes
#
CLIDIR=/usr/local/pub/root/gsilibs/hrevcli/v10/inc


case "$1" in
  223-12)
  GSIDIR=/usr/local/pub/root/gsilibs/new 
  . rootlogin 223-12;;
  224-04)
  GSIDIR=/usr/local/pub/root/gsilibs/224-04 
  . rootlogin 224-04;;
  224-05) 
  GSIDIR=/usr/local/pub/root/gsilibs/224-05 
  . rootlogin 224-05;;
  225-03) 
  GSIDIR=/d/hades/denis/hrevcli/225-03
  . rootlogin 225-03;;

esac

 
if [[ -d  $GSIDIR ]]
then
 print " gsi online lib found ==> " 
 print $GSIDIR
 export GSIDIR
else
 print " can not find  gsi online lib"
 return
fi

if [[ -d  $CLIDIR ]]
then
 print " gsi online sources found ==> "
 print $CLIDIR
 export CLIDIR
else
 print "can not find  gsi online lib "
 return
fi

if [[ -d  $HADDIR/evtserver ]]
then
 print " "
else 
 print " evtserver branch is missing in " 
 print $HADDIR/base
 print "can not initialise online-Hydra"
 return
fi

export ONLINEHYDRA=on
print "############################"
print "init online-Hydra done "
print " for root version  === > " $ROOTSYS
print "############################"














