##############################################################################
#
#  Makefile for Hydra library libHodo.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Hodo

SOURCE_FILES :=	hhodocontfact.cc	\
		hhododetector.cc	\
		hhododummy.cc		\
		hhodolookup.cc		\
		hhodoparasciifileio.cc	\
		hhodoparrootfileio.cc	\
		hhodoraw.cc		\
		hhodotaskset.cc		\
		hhodounpacker.cc	\
		hhodocal.cc		\
		hhodocalibrater.cc	\
		hhodocalpar.cc		\
		hhodohit2start.cc	\
		hstart2hodo.cc		\
		hhodohit.cc		\
		hhodohitffiber.cc	\
		hhodohitfdiamond.cc	\
		hhodorefhitpar.cc	\
		hhodotrbunpacker.cc	\
		hhodopionmom.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
