/* Generated by Together */

#ifndef TGO4TOFONLINESLOTS_H
#define TGO4TOFONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4TofOnline;
class TGo4GUIRegistry;
class TGo4TofOnlineStatus;
class TQRootCanvas;
class TPad;

class TGo4TofOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4TofOnlineSlots();
    TGo4TofOnlineSlots(const Char_t * name, const Char_t * title, TGo4TofOnline * p);

    void SetGUI(TGo4TofOnline *);
    TGo4TofOnline *GetGUI(){return fxTGo4TofOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void AddObject(TNamed * ,TQRootCanvas*,TPad*);
    void UpdateGUI(TObject*);
    ClassDef(TGo4TofOnlineSlots, 1);
    
private:    
    TGo4TofOnline *fxTGo4TofOnline; //!
    TGo4TofOnlineStatus *fxTGo4TofOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4TOFONLINESLOTS_H
