#include "metamatch.h"
//Class for matching mdc segments with META.
////
///BECAUSE OF THE LITTLE TIME AVAILABLE I INCLUDED THIS TASK IN HSPLINETRACKF TASK,
///JUST UNTILL THE END OF BEEMTIME AFTERWARDS IT WILL BE IN CORRECT PLEACE. SORRY.
//
//
//
//
//
//
//
//
//
//
