##############################################################################
#
#  Makefile for Hydra library libMdcTrackG.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := MdcTrackG

SOURCE_FILES :=	hmdctrackgfield.cc		\
		hmdctrackgcorrections.cc	\
		hmdctrackgcorrpar.cc		\
		hmdctrackgfieldpar.cc		\
		hmdctrackgspline.cc		\
		hmdctrackgcontfact.cc		\
		hbasetrack.cc			\
		hmetamatch.cc			\
		hmetamatchF.cc			\
		hmetamatchpar.cc		\
		hsplinetrack.cc			\
		hsplinetrackF.cc		\
		hkicktrackB.cc			\
		hkicktracksimB.cc		\
		hkicktrack123B.cc		\
		hkicktrackbaseF.cc		\
		hrungekutta.cc			\
		hrktrackB.cc			\
		hrktrackBF.cc			\
		hsplinetaskset.cc		\
		hsplinetofclF.cc		\
		htofrec.cc			\
		henergylosscorrpar.cc           \
		hsplinepar.cc
# not included in the Makefile, but not removed from CVS
#		hmdctrackgsplinecorr.cc
#		hmdctrackgmatch.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
