##############################################################################
#
#  Makefile for Hydra library libMdcTrackS.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := MdcTrackS

SOURCE_FILES :=	hmdccal3.cc		\
		hmdccal3sim.cc		\
		hmdccaltable.cc		\
		hmdchitaux.cc		\
		hmdchitauxsim.cc	\
		hmdchitcomp.cc		\
		hmdchitf.cc		\
		hmdchitfpar.cc		\
		hmdchitfsim.cc		\
		hmdchitsfilter.cc	\
		hmdctrackscontfact.cc	\
		hmdcleverarmgeometry.cc	\
		hmdcmodulegeometry.cc	\
		hmdcsegmentf.cc		\
		hmdcsegmentfpar.cc	\
		hmdctargetgeometry.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
