/* Generated by Together */

#ifndef TGO4HADESONLINEPANELSTATUS_H
#define TGO4HADESONLINEPANELSTATUS_H
#include "Go4StatusBase/TGo4Status.h"
#include "TObjArray.h"
#include "TIterator.h"
#include "TObject.h"

class TGo4HadesOnlinePanelStatus : public TGo4Status {
public:    

    ~TGo4HadesOnlinePanelStatus();    

    TGo4HadesOnlinePanelStatus(Text_t *Name, Text_t * Title);
    TObject*  OverWriteLocalObject(TNamed * fxData_Local);
    TIterator *GetLocalListIter(){return LocalListIter;}
    TObjArray *GetLocalListStatus();
    TObject* GetObjectfromLocalList(const Char_t *ObjectAt);
    ClassDef(TGo4HadesOnlinePanelStatus,1);

private:
	
	TObjArray *LocalListContent;
	TIterator* LocalListIter;        
    
};
#endif //TGO4HADESONLINEPANELSTATUS_H
