##############################################################################
#
#  Makefile for Hydra library libHyp.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := Hyp

SOURCE_FILES :=	hhypbasealgorithm.cc		\
		hhypreconstructor.cc		\
		hhypchannel.cc			\
		hhypcomb.cc			\
		hhypkine.cc			\
		hhyplist.cc			\
		hhyplistfiller.cc		\
		hhypmultichannelfiller.cc	\
		hhypMultiChannelP3N1Alg.cc	\
		hhyplistfillerinclusive.cc	\
		hhypPPPipPimXAlg.cc		\
		hhypPPPipPimProjector.cc	\
		hhypPPPipPimPi0Alg.cc		\
		hhypPPPipPimMppMinvAlg.cc	\
		hhypPPPipPimGammaAlg.cc		\
		hhypPPEpEmXAlg.cc		\
		hhypPEpEmXAlg.cc		\
		hhypPPEpEmGammaAlg.cc		\
		hhypPPEpEmProjector.cc		\
		hhypPPEpEmGammaProjector.cc	\
		hhypPEpEmProjector.cc           \
		hhypPPXAlg.cc			\
		hhypPPElasticAlg.cc		\
		hhypPPProjector.cc		\
		hhypPPPipPimPi0Kine.cc		\
		hhypPPPipPimGammaKine.cc	\
		hhypPPEpEmGammaKine.cc		\
		hhypQA.cc			\
		hhypHardCutsAlg.cc		\
		hhypDeltaTofAlg.cc		\
		hhyprecpar.cc			\
		hhypcontfact.cc			\
		hhypPPKpPimXAlg.cc		\
		hhypPPKpPimMiss0Alg.cc		\
		hhypPPKpPimProjector.cc		\
		hpidtofinocorr.cc		\
		hhypPPKpPimMiss0Projector.cc	\
		hhypPKpLambdaMiss0Alg.cc	\
		hhypPKpLambdaMiss0Projector.cc	\
		hhypKineFit.cc			\
		hhypKineFitPPPipPimPi0.cc	\
		hhypKineFitPPPipPimGamma.cc	\
		hhypKineFitPPEpEmGamma.cc	\
		hhypPPPi0Alg.cc			\
		hhypPPPi0Projector.cc           \
		hhypPPipProjector.cc            \
		hhypPPipAlg.cc                  \
		hhypPidMomBeta.cc
# files not included in build process but still in CVS
#
#hhypKineFitEta.cc
#hhypKineRefitUtils.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
