##############################################################################
#
#  Makefile for Hydra library libMdcUtil.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := MdcUtil

SOURCE_FILES :=	hmdcfilltime1hists.cc		\
		hmdclowlevelqa.cc		\
		hmdcmonitor.cc			\
		hmdcoffset.cc			\
		hmdcoffsetchecktimeshift.cc	\
		hmdcslope.cc			\
		hmdcselftracking.cc		\
		hmdctrigger.cc			\
		hmdcslopes.cc			\
		hmdchitindexcorr.cc		\
		hmdctrackingeff.cc
# removed from Makefile, but not from CVS
#		hmdcwireoffset.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
