/* Generated by Together */

#ifndef TGO4HADESONLINESLOTS_H
#define TGO4HADESONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4HadesOnline;
class TGo4GUIRegistry;
class TGo4HadesOnlineStatus;

class TGo4HadesOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4HadesOnlineSlots();    
    TGo4HadesOnlineSlots(const char * name, const char * title, TGo4HadesOnline * p);	

    void SetGUI(TGo4HadesOnline *);
    TGo4HadesOnline *GetGUI(){return fxTGo4HadesOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void UpdateGUI(const char *ObjName);
    ClassDef(TGo4HadesOnlineSlots, 1);
    
private:    
    TGo4HadesOnline *fxTGo4HadesOnline; //!
    TGo4HadesOnlineStatus *fxTGo4HadesOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4HADESONLINESLOTS_H
