/* Generated by Together */

#ifndef TGO4HADESCONFIGSTATUS_H
#define TGO4HADESCONFIGSTATUS_H
#include "Go4StatusBase/TGo4Status.h"


class TGo4HadesConfigStatus : public TGo4Status {
public:    

    ~TGo4HadesConfigStatus();    
     TGo4HadesConfigStatus(Text_t *Name, Text_t * Title);
     void SetActiveConfig(TNamed *fxdata){fxConfig = fxdata;}
     TNamed *GetConfig(){return fxConfig;}
     ClassDef(TGo4HadesConfigStatus,1);

private:
     TNamed *fxConfig;
    
};
#endif //TGO4HADESCONFIGSTATUS_H
