##############################################################################
#
#  Makefile for Hydra library libRichUtil.so
#
#  This makefile contains all definitions local to this module. All
#  general definitions are included from makefiles in $(HADDIR).
#
##############################################################################

LIB_NAME := RichUtil

SOURCE_FILES :=	hgeantparticleinfo.cc		\
	        hrichevtmixer.cc		\
	        hrichhistofiller.cc		\
	        hrichcorrelator.cc		\
	        hrichpca.cc			\
	        hrichcuttrackletsim.cc		\
	        hrichcutpairsim.cc		\
	        hrichmon.cc			\
	        hrichpcasim.cc			\
	        hrichpaircreator.cc		\
	        hrichpaircreatorsim.cc		\
	        hrichcut.cc			\
	        hrichcorrelatorsim.cc		\
	        hrichdirclus.cc			\
	        hrichhistfac.cc			\
	        hdihitmatch.cc			\
	        hdihitmatchsim.cc		\
	        hrichcorrcounter.cc		\
	        hrichcorrcountersim.cc		\
	        hrichtrackletfilter.cc		\
	        hrichtrackletfiltersim.cc	\
	        hrichevtfilter.cc		\
	        hrichevtfiltersim.cc		\
	        htrackinfo.cc			\
	        hgeantkineana.cc		\
	        hrichpairana.cc			\
	        hrichpairanasim.cc		\
	        hhitmatch.cc			\
	        hhitmatchsim.cc			\
	        hhitmatchheadersim.cc		\
	        hhitmatchheader.cc		\
	        hrichdumphit.cc			\
	        hrichdumphitsim.cc		\
	        hrichdumpcal.cc			\
	        hrichdumpraw.cc			\
	        hrichlocal.cc			\
	        hrichsender.cc			\
	        hrichsendercal.cc		\
	        hrichsenderraw.cc		\
	        hrichsenderrawaccu.cc		\
	        hrichphotonfinder.cc		\
	        hrichphotonhit.cc		\
	        hrichphotonhitheader.cc		\
	        hrichdisplaycal.cc		\
	        hrichdisplayraw.cc		\
	        hrichhitfit.cc			\
	        hrichchernovringfitter.cc	\
	        hrichrecalibrater.cc		\
	        hrichlocalmaxcal.cc		\
	        hrichlocalmaxsim.cc		\
	        hrichcalmax.cc			\
	        hrichutilfunc.cc		\
	        hconstant.cc			\
	        hrichdiag.cc			\
                hrichcategoryviewer.cc		\
	        hrichlocalmaxheader.cc		\
	        hrichN0cal.cc			\
	        hlocalselection.cc		\
	        hlocalshift.cc			\
		hphotoncluster.cc		\
		hclusterselector.cc		\
		hclusterselectorsim.cc		\
		hthreseval.cc			\
		hpidrichtable.cc		\
		hcreatecorrpar.cc		\
		hrichselector.cc		\
# removed from Makefile, but not from CVS
#		hrichclustercal.cc		\
#		hrichclusterraw.cc		\
#		hrichclustersim.cc		\
#		hrichglobal.cc			\
#		hrichlocalmaxraw.cc		\
#		hrichphotoncal.cc		\
#		hrichphotonraw.cc		\
#		hrichphotonsim.cc

include $(HADDIR)/hades.def.mk
include $(HADDIR)/hades.module.mk
