/* Generated by Together */

#include "TGo4StartOnlineStatus.h"
#include "Go4LockGuard/TGo4LockGuard.h"
#include "TH1.h"
#include "TNamed.h"
#include "hmonhist.h"

TGo4StartOnlineStatus::TGo4StartOnlineStatus(Text_t *Name, Text_t * Title)
    :TGo4Status(Name)
{
  	TGo4LockGuard Global;
  	LocalListContent=new TObjArray();
  	LocalListIter = LocalListContent->MakeIterator();	

}
	TGo4StartOnlineStatus::~TGo4StartOnlineStatus()
{

}
void TGo4StartOnlineStatus::OverWriteLocalObject(TNamed * fxData_Local)
{
	
 	TGo4LockGuard Global;
	TObject* OldLocalObject=0;
	OldLocalObject=LocalListContent->FindObject(fxData_Local->GetName());
	
	if( OldLocalObject==0) {
	
	       		LocalListContent->AddLast(fxData_Local->Clone());
	}else if(OldLocalObject->InheritsFrom("HMonHistAddon")){

	    HMonHistAddon* h=(HMonHistAddon*)OldLocalObject;
	    h->reset(0,0);
            h->add((HMonHistAddon*)fxData_Local);
	}else {
		LocalListContent->Remove(OldLocalObject);
		LocalListContent->Compress();
		LocalListContent->Expand(LocalListContent->GetLast()+1);
		delete OldLocalObject;
		LocalListContent->AddLast(fxData_Local->Clone());
	}
}

TObjArray *TGo4StartOnlineStatus::GetLocalListStatus()
{
  	TGo4LockGuard Global;	
  	return(LocalListContent);
}

TObject* TGo4StartOnlineStatus::GetObjectfromLocalList(const char *Object)
{
  	TGo4LockGuard Global;
  	return(LocalListContent->FindObject(Object));
	
}
ClassImp(TGo4StartOnlineStatus)
