/* Generated by Together */

#ifndef TGO4RICHONLINESTATUS_H
#define TGO4RICHONLINESTATUS_H
#include "Go4StatusBase/TGo4Status.h"
#include "TObjArray.h"
#include "TIterator.h"
#include "TObject.h"

class TGo4RichOnlineStatus : public TGo4Status {
public:    

    ~TGo4RichOnlineStatus();

    TGo4RichOnlineStatus(Text_t *Name, Text_t * Title);
    void OverWriteLocalObject(TNamed * fxData_Local);
    TIterator *GetLocalListIter(){return LocalListIter;}
    TObjArray *GetLocalListStatus();
    TObject* GetObjectfromLocalList(const char *ObjectAt);
    ClassDef(TGo4RichOnlineStatus,1);

private:
	
	TObjArray *LocalListContent;
	TIterator* LocalListIter;        
    
};
#endif //TGO4RICHONLINESTATUS_H
