/* Generated by Together */

#ifndef TGO4HADESCONFIGSLOTS_H
#define TGO4HADESCONFIGSLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4HadesConfig;
class TGo4GUIRegistry;
class TGo4HadesConfigStatus;

class TGo4HadesConfigSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4HadesConfigSlots();    
    TGo4HadesConfigSlots(const char * name, const char * title, TGo4HadesConfig * p);	

    void SetGUI(TGo4HadesConfig *);
    TGo4HadesConfig *GetGUI(){return fxTGo4HadesConfig; }
    TGo4Status * GetStatus();

    void Start();
    void AddObject(TNamed * );
    void UpdateGUI(const char *ObjName);
    ClassDef(TGo4HadesConfigSlots, 1);
    
private:    
    TGo4HadesConfig *fxTGo4HadesConfig; //!
    TGo4HadesConfigStatus *fxTGo4HadesConfigStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4HADESCONFIGSLOTS_H
