/* Generated by Together */

#ifndef TGO4STARTONLINESLOTS_H
#define TGO4STARTONLINESLOTS_H
#include "Go4GUIBase/TGo4SlotsBaseClass.h"
#include "TObject.h"
class TNamed;
class TGo4Status;
class TGo4EditPolyCond;
class TGo4StartOnline;
class TGo4GUIRegistry;
class TGo4StartOnlineStatus;

class TGo4StartOnlineSlots : public TGo4SlotsBaseClass {
public:    

    ~TGo4StartOnlineSlots();
    TGo4StartOnlineSlots(const char * name, const char * title, TGo4StartOnline * p);

    void SetGUI(TGo4StartOnline *);
    TGo4StartOnline *GetGUI(){return fxTGo4StartOnline; }
    TGo4Status * GetStatus();

    void StartMonitor();
    void StopMonitor(); 
    void Reset();
 
    void AddObject(TNamed * );
    void UpdateGUI(const char *ObjName);
    ClassDef(TGo4StartOnlineSlots, 1);
    
private:    
    TGo4StartOnline *fxTGo4StartOnline; //!
    TGo4StartOnlineStatus *fxTGo4StartOnlineStatus; //!
    TGo4GUIRegistry  *fxTGo4GUIRegistry; //!
};
#endif //TGO4STARTONLINESLOTS_H
